# Generated by Django 4.2.7 on 2024-05-24 03:06

from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embed_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='文件名称')),
                ('file', models.FileField(storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-private'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='文件')),
            ],
            options={
                'verbose_name': '知识',
                'verbose_name_plural': '知识',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseFolder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='知识库名称')),
                ('description', models.TextField(verbose_name='知识库描述')),
                ('embed_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embed_mgmt.embedprovider', verbose_name='嵌入模型')),
                ('knowledges', models.ManyToManyField(blank=True, null=True, to='knowledge_mgmt.knowledge', verbose_name='知识')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
            },
        ),
    ]
