# Generated by Django 4.2.7 on 2024-05-24 14:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embed_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseFolder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('train_status', models.IntegerField(choices=[(0, '待训练'), (1, '处理中'), (2, '完成'), (3, '失败')], default=0, verbose_name='状态')),
                ('train_progress', models.FloatField(default=0, verbose_name='进度')),
                ('chunk_size', models.IntegerField(default=1000, verbose_name='分块大小')),
                ('chunk_overlap', models.IntegerField(default=100, verbose_name='分块重叠')),
                ('enable_general_parse', models.BooleanField(default=True, verbose_name='常规解析')),
                ('embed_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embed_mgmt.embedprovider', verbose_name='嵌入模型')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='文件名称')),
                ('file', models.FileField(storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-private'), upload_to=django_minio_backend.models.iso_date_prefix, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['md', 'docx', 'xlsx', 'csv', 'pptx', 'pdf', 'txt'])], verbose_name='文件')),
                ('knowledge_base_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_mgmt.knowledgebasefolder', verbose_name='知识')),
            ],
            options={
                'verbose_name': '知识',
                'verbose_name_plural': '知识',
            },
        ),
    ]
