# Generated by Django 4.2.7 on 2024-05-24 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebasefolder',
            name='knowledges',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='knowledge_base_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_mgmt.knowledgebasefolder', verbose_name='知识'),
        ),
    ]
