# Generated by Django 4.2.7 on 2024-05-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_mgmt', '0002_remove_knowledgebasefolder_knowledges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='train_progress',
            field=models.FloatField(default=0, verbose_name='训练进度'),
        ),
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='train_status',
            field=models.BooleanField(default=False, verbose_name='训练状态'),
        ),
    ]
