# Generated by Django 4.2.7 on 2024-05-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_mgmt', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='enable_text_search',
            field=models.BooleanField(default=True, verbose_name='文本检索'),
        ),
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='enable_vector_search',
            field=models.BooleanField(default=True, verbose_name='向量检索'),
        ),
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='rag_k',
            field=models.IntegerField(default=5, verbose_name='返回结果数量'),
        ),
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='rag_num_candidates',
            field=models.IntegerField(default=1000, verbose_name='候选数量'),
        ),
    ]
