# Generated by Django 4.2.7 on 2024-09-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_mgmt", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="rag_k",
            field=models.IntegerField(default=50, verbose_name="返回结果数量"),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="rag_num_candidates",
            field=models.IntegerField(default=1000, verbose_name="候选数量"),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="name"),
        ),
    ]
