# Generated by Django 4.2.7 on 2024-09-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_mgmt", "0003_knowledgebase_rag_k_knowledgebase_rag_num_candidates_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="knowledgebase",
            options={"verbose_name": "Maintainer Fields"},
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="train_status",
            field=models.IntegerField(
                choices=[(0, "Training"), (1, "Ready"), (2, "Error"), (3, "Pending")],
                default=0,
                verbose_name="train status",
            ),
        ),
    ]
