# Generated by Django 4.2.7 on 2024-05-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_mgmt', '0003_knowledgebasefolder_train_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasefolder',
            name='train_status',
            field=models.IntegerField(choices=[(0, '待训练'), (1, '处理中'), (2, '完成'), (3, '失败')], default=0, verbose_name='训练状态'),
        ),
    ]
