# Generated by Django 4.2.7 on 2024-09-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_mgmt", "0004_alter_knowledgebase_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="text_search_mode",
            field=models.CharField(default="match", max_length=20, verbose_name="Text search mode"),
        ),
    ]
