# Generated by Django 4.2.7 on 2024-05-24 09:45

import django.core.validators
from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_mgmt', '0005_alter_knowledge_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='file',
            field=models.FileField(storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-private'), upload_to=django_minio_backend.models.iso_date_prefix, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['md', 'docx', 'xlsx', 'csv', 'pptx', 'pdf', 'txt'])], verbose_name='文件'),
        ),
    ]
