# Generated by Django 4.2.7 on 2024-05-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('embed_model', models.CharField(choices=[('fastembed', 'FastEmbed')], max_length=255, verbose_name='嵌入模型')),
                ('embed_config', models.JSONField(blank=True, null=True, verbose_name='嵌入配置')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'Embed模型',
                'verbose_name_plural': 'Embed模型',
            },
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('llm_model', models.CharField(choices=[('gpt-3.5-turbo-16k', 'GPT-3.5 Turbo 16K')], max_length=255, verbose_name='LLM模型')),
                ('llm_config', models.JSONField(blank=True, null=True, verbose_name='LLM配置')),
            ],
            options={
                'verbose_name': 'LLM模型',
                'verbose_name_plural': 'LLM模型',
            },
        ),
    ]
