# Generated by Django 4.2.7 on 2024-05-26 12:11

from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models
import django_yaml_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel_mgmt', '0001_initial'),
        ('knowledge_mgmt', '0001_initial'),
        ('model_provider_mgmt', '0002_alter_embedprovider_embed_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': '扩展包',
                'verbose_name_plural': '扩展包',
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='意图名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('content_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentpack_mgmt.contentpack', verbose_name='扩展包')),
            ],
            options={
                'verbose_name': '意图',
                'verbose_name_plural': '意图',
            },
        ),
        migrations.CreateModel(
            name='RasaResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='回复名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('response', django_yaml_field.fields.YAMLField(verbose_name='回复')),
                ('content_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentpack_mgmt.contentpack', verbose_name='扩展包')),
            ],
            options={
                'verbose_name': '回复',
                'verbose_name_plural': '回复',
            },
        ),
        migrations.CreateModel(
            name='RasaStories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='故事名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('story', django_yaml_field.fields.YAMLField(verbose_name='故事')),
                ('content_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentpack_mgmt.contentpack', verbose_name='扩展包')),
            ],
            options={
                'verbose_name': '故事',
                'verbose_name_plural': '故事',
            },
        ),
        migrations.CreateModel(
            name='RasaSlots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='槽位名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('slot', django_yaml_field.fields.YAMLField(verbose_name='槽位')),
                ('content_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentpack_mgmt.contentpack', verbose_name='扩展包')),
            ],
            options={
                'verbose_name': '槽位',
                'verbose_name_plural': '槽位',
            },
        ),
        migrations.CreateModel(
            name='RasaRules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('rule_steps', django_yaml_field.fields.YAMLField(verbose_name='规则')),
                ('content_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentpack_mgmt.contentpack', verbose_name='扩展包')),
            ],
            options={
                'verbose_name': '规则',
                'verbose_name_plural': '规则',
            },
        ),
        migrations.CreateModel(
            name='RasaResponseCorpus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('corpus', models.TextField(verbose_name='语料')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentpack_mgmt.rasaresponse', verbose_name='回复')),
            ],
            options={
                'verbose_name': '回复语料',
                'verbose_name_plural': '回复语料',
            },
        ),
        migrations.CreateModel(
            name='RasaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='模型名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('model_file', models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-private'), upload_to='rasa_models', verbose_name='文件')),
                ('pipeline_config', django_yaml_field.fields.YAMLField(default='', verbose_name='模型配置')),
                ('policies_config', django_yaml_field.fields.YAMLField(default='', verbose_name='策略配置')),
                ('content_packs', models.ManyToManyField(blank=True, null=True, to='contentpack_mgmt.contentpack', verbose_name='扩展包')),
            ],
            options={
                'verbose_name': '模型',
                'verbose_name_plural': '模型',
            },
        ),
        migrations.CreateModel(
            name='RasaForms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='表单名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('form', django_yaml_field.fields.YAMLField(verbose_name='表单')),
                ('content_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentpack_mgmt.contentpack', verbose_name='扩展包')),
            ],
            options={
                'verbose_name': '表单',
                'verbose_name_plural': '表单',
            },
        ),
        migrations.CreateModel(
            name='RasaEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='实体名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('content_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentpack_mgmt.contentpack', verbose_name='扩展包')),
            ],
            options={
                'verbose_name': '实体',
                'verbose_name_plural': '实体',
            },
        ),
        migrations.CreateModel(
            name='IntentCorpus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('corpus', models.TextField(verbose_name='语料')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentpack_mgmt.intent', verbose_name='意图')),
            ],
            options={
                'verbose_name': '意图语料',
                'verbose_name_plural': '意图语料',
            },
        ),
        migrations.CreateModel(
            name='BotActions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('action_llm_fallback', '开放型对话'), ('action_external_utter', '人工介入')], max_length=255, verbose_name='技能名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('action_prompt', models.TextField(blank=True, null=True, verbose_name='动作提示词')),
                ('enable_conversation_history', models.BooleanField(default=False, verbose_name='启用对话历史')),
                ('conversation_window_size', models.IntegerField(default=10, verbose_name='对话窗口大小')),
                ('enable_rag', models.BooleanField(default=False, verbose_name='启用RAG')),
                ('rag_top_k', models.IntegerField(default=5, verbose_name='RAG返回结果数量')),
                ('rag_num_candidates', models.IntegerField(default=1000, verbose_name='RAG向量候选数量')),
                ('content_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentpack_mgmt.contentpack', verbose_name='扩展包')),
                ('knowledge_base_folders', models.ManyToManyField(blank=True, null=True, to='knowledge_mgmt.knowledgebasefolder', verbose_name='知识库')),
                ('llm_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_provider_mgmt.llmmodel', verbose_name='LLM模型')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
            },
        ),
        migrations.CreateModel(
            name='BotActionRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='技能提示词')),
                ('bot_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentpack_mgmt.botactions', verbose_name='技能')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channel_mgmt.channel', verbose_name='生效通道')),
                ('rule_user', models.ManyToManyField(blank=True, null=True, to='channel_mgmt.channeluser', verbose_name='生效用户')),
                ('rule_user_groups', models.ManyToManyField(blank=True, null=True, to='channel_mgmt.channelusergroup', verbose_name='生效用户组')),
            ],
            options={
                'verbose_name': '技能规则',
                'verbose_name_plural': '技能规则',
            },
        ),
    ]
