# Generated by Django 4.2.7 on 2024-05-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentpack_mgmt', '0002_remove_rasaresponse_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpack',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='contentpack',
            name='name',
            field=models.CharField(max_length=255, verbose_name='扩展包名称'),
        ),
    ]
