# Generated by Django 4.2.7 on 2024-05-27 08:01

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('contentpack_mgmt', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasamodel',
            name='train_data_file',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-private'), upload_to='rasa_train_data', verbose_name='训练数据'),
        ),
    ]
