# Generated by Django 4.2.7 on 2024-05-26 12:42

from django.db import migrations
import django_yaml_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contentpack_mgmt', '0003_alter_contentpack_description_alter_contentpack_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasaforms',
            name='form',
            field=django_yaml_field.fields.YAMLField(default={'form_name': {'required_slots': ['slot_name']}}, verbose_name='表单'),
        ),
        migrations.AlterField(
            model_name='rasamodel',
            name='pipeline_config',
            field=django_yaml_field.fields.YAMLField(default={'pipeline': [{'case_sensitive': True, 'name': 'KeywordIntentClassifier'}, {'ambiguity_threshold': 0.1, 'name': 'FallbackClassifier', 'threshold': 0.7}]}, verbose_name='模型配置'),
        ),
        migrations.AlterField(
            model_name='rasamodel',
            name='policies_config',
            field=django_yaml_field.fields.YAMLField(default={'policies': [{'core_fallback_action_name': 'action_llm_fallback', 'core_fallback_threshold': 0.4, 'name': 'RulePolicy'}]}, verbose_name='策略配置'),
        ),
        migrations.AlterField(
            model_name='rasarules',
            name='rule_steps',
            field=django_yaml_field.fields.YAMLField(default={'steps': [{'intent': 'intent_name'}]}, verbose_name='规则'),
        ),
        migrations.AlterField(
            model_name='rasaslots',
            name='slot',
            field=django_yaml_field.fields.YAMLField(default={'slot_name': {'influence_conversation': True, 'mappings': [{'type': 'custom'}], 'type': 'text'}}, verbose_name='槽位'),
        ),
        migrations.AlterField(
            model_name='rasastories',
            name='story',
            field=django_yaml_field.fields.YAMLField(default={'steps': [{'intent': 'intent_name'}]}, verbose_name='故事'),
        ),
    ]
