# Generated by Django 4.2.7 on 2024-05-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('embed_model', models.CharField(choices=[('fastembed', 'FastEmbed')], max_length=255, verbose_name='嵌入模型')),
                ('embed_config', models.JSONField(blank=True, null=True, verbose_name='嵌入配置')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '嵌入模型',
                'verbose_name_plural': '嵌入模型',
            },
        ),
    ]
