# Generated by Django 4.2.7 on 2024-08-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAPISecret",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("username", models.CharField(max_length=255, unique=True)),
                ("api_secret", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "时间相关字段",
                "abstract": False,
            },
        ),
    ]
