# Generated by Django 4.2.7 on 2024-09-03 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userapisecret",
            options={"verbose_name": "Time Fields"},
        ),
    ]
