# Generated by Django 4.2.7 on 2024-09-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_userapisecret_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapisecret",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time"),
        ),
        migrations.AlterField(
            model_name="userapisecret",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
        ),
    ]
