FILE_CHUNK_SERIVCE_URL = "http://chunk-server/file_chunk"
MANUAL_CHUNK_SERVICE_URL = "http://chunk-server/manual_chunk"
WEB_PAGE_CHUNK_SERVICE_URL = "http://chunk-server/webpage_chunk"
OPENAI_CHAT_SERVICE_URL = "http://chat-server/openai"
REMOTE_INDEX_URL = "http://rag-server/elasticsearch_index"
RAG_SERVER_URL = "http://rag-server/elasticsearch_rag"
ONLINE_SEARCH_SERVER_URL = "http://rag-server/online_search"
