# Generated by Django 4.2.7 on 2024-05-26 11:44

import apps.core.encoders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedprovider',
            name='embed_config',
            field=models.JSONField(blank=True, default=dict, encoder=apps.core.encoders.PrettyJSONEncoder, null=True, verbose_name='嵌入配置'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='llm_config',
            field=models.JSONField(blank=True, default=dict, encoder=apps.core.encoders.PrettyJSONEncoder, null=True, verbose_name='LLM配置'),
        ),
    ]
