# Generated by Django 4.2.7 on 2024-09-25 02:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("model_provider_mgmt", "0002_llmskill_groups_llmskill_introduction_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="llmskill",
            old_name="groups",
            new_name="team",
        ),
    ]
