# Generated by Django 4.2.7 on 2024-09-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_provider_mgmt", "0003_rename_groups_llmskill_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmskill",
            name="rag_score_threshold_map",
            field=models.JSONField(default=dict, verbose_name="知识库RAG分数阈值映射"),
        ),
        migrations.RemoveField(
            model_name="llmskill",
            name="rag_score_threshold",
        ),
    ]
