# Generated by Django 4.2.7 on 2024-09-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_provider_mgmt", "0004_llmskill_rag_score_threshold_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmskill",
            name="temperature",
            field=models.FloatField(default=0.7, verbose_name="温度"),
        ),
    ]
