# Generated by Django 4.2.7 on 2024-05-26 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_mgmt', '0001_initial'),
        ('llm_mgmt', '0002_alter_embedprovider_embed_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '机器人',
                'verbose_name_plural': '机器人',
            },
        ),
        migrations.CreateModel(
            name='BotSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='技能名称')),
                ('skill_id', models.CharField(default='', max_length=255, verbose_name='技能ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('skill_prompt', models.TextField(blank=True, null=True, verbose_name='技能提示词')),
                ('enable_conversation_history', models.BooleanField(default=False, verbose_name='启用对话历史')),
                ('conversation_window_size', models.IntegerField(default=10, verbose_name='对话窗口大小')),
                ('enable_rag', models.BooleanField(default=False, verbose_name='启用RAG')),
                ('rag_top_k', models.IntegerField(default=5, verbose_name='RAG返回结果数量')),
                ('rag_num_candidates', models.IntegerField(default=1000, verbose_name='RAG向量候选数量')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_mgmt.bot', verbose_name='机器人')),
                ('knowledge_base_folders', models.ManyToManyField(blank=True, null=True, to='knowledge_mgmt.knowledgebasefolder', verbose_name='知识库')),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm_mgmt.llmmodel', verbose_name='LLM模型')),
            ],
            options={
                'verbose_name': '机器人技能',
                'verbose_name_plural': '机器人技能',
            },
        ),
        migrations.CreateModel(
            name='BotSkillRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='技能提示词')),
                ('bot_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_mgmt.botskill', verbose_name='技能')),
            ],
            options={
                'verbose_name': '规则',
                'verbose_name_plural': '规则',
            },
        ),
    ]
