# Generated by Django 4.2.7 on 2024-05-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_mgmt', '0001_initial'),
        ('bot_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='channels',
            field=models.ManyToManyField(to='channel_mgmt.channel', verbose_name='通道'),
        ),
    ]
