# Generated by Django 4.2.7 on 2024-05-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('channel_type', models.CharField(choices=[('enterprise_wechat', '企业微信'), ('enterprise_wechat_bot', '企业微信机器人'), ('ding_talk', '钉钉'), ('web', 'Web')], max_length=100, verbose_name='类型')),
                ('channel_config', models.JSONField(verbose_name='通道配置')),
            ],
            options={
                'verbose_name': '消息通道',
                'verbose_name_plural': '消息通道',
            },
        ),
    ]
